"""New Migration2

Revision ID: 0f8abd56eee8
Revises: e61815ea606d
Create Date: 2023-05-12 08:32:16.454883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8abd56eee8'
down_revision = 'e61815ea606d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tracking', sa.Column('UserID', sa.String(), nullable=True))
    op.add_column('Tracking', sa.Column('QRID', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Tracking', 'QR', ['QRID'], ['QRID'])
    op.create_foreign_key(None, 'Tracking', 'user', ['UserID'], ['UserID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tracking', type_='foreignkey')
    op.drop_constraint(None, 'Tracking', type_='foreignkey')
    op.drop_column('Tracking', 'QRID')
    op.drop_column('Tracking', 'UserID')
    # ### end Alembic commands ###
