"""New Migration

Revision ID: 13951b066554
Revises: cee7ca416950
Create Date: 2023-05-14 19:32:24.382406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13951b066554'
down_revision = 'cee7ca416950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
