"""New Migration

Revision ID: 45f4d16d18ae
Revises: 8e5f00d45ad0
Create Date: 2023-05-12 10:54:33.435270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f4d16d18ae'
down_revision = '8e5f00d45ad0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tracking', 'Timestamp')
    op.add_column('Tracking', sa.Column('Timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tracking', 'Timestamp')
    # ### end Alembic commands ###
