"""New Migration

Revision ID: 45f53a8dd800
Revises: 45f4d16d18ae
Create Date: 2023-05-14 19:19:51.905990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f53a8dd800'
down_revision = '45f4d16d18ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
