"""New Migration2

Revision ID: 4e9d1887afdf
Revises: d6475546a69e
Create Date: 2023-05-12 10:35:11.032719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9d1887afdf'
down_revision = 'd6475546a69e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
