"""New Migration

Revision ID: 626f90c845e1
Revises: 
Create Date: 2023-05-12 08:09:29.649790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626f90c845e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('QR_LocationID_fkey', 'QR', type_='foreignkey')
    op.drop_column('QR', 'LocationID')
    op.drop_constraint('QR', 'Tracking', type_='foreignkey')
    op.drop_constraint('user', 'Tracking', type_='foreignkey')
    op.drop_column('Tracking', 'UserID')
    op.drop_column('Tracking', 'QRID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tracking', sa.Column('QRID', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Tracking', sa.Column('UserID', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('user', 'Tracking', 'user', ['UserID'], ['UserID'])
    op.create_foreign_key('QR', 'Tracking', 'QR', ['QRID'], ['QRID'])
    op.add_column('QR', sa.Column('LocationID', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('QR_LocationID_fkey', 'QR', 'Location', ['LocationID'], ['LocationID'])
    # ### end Alembic commands ###
