"""New Migration

Revision ID: 6af7afb1b88f
Revises: 45f53a8dd800
Create Date: 2023-05-14 19:22:23.601729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af7afb1b88f'
down_revision = '45f53a8dd800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
