"""New Migration

Revision ID: 763d96143454
Revises: 13951b066554
Create Date: 2023-05-14 19:34:32.913470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763d96143454'
down_revision = '13951b066554'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
