"""New Migration

Revision ID: 8e5f00d45ad0
Revises: 4e9d1887afdf
Create Date: 2023-05-12 10:50:38.021069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5f00d45ad0'
down_revision = '4e9d1887afdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
