"""New Migration

Revision ID: cee7ca416950
Revises: 6af7afb1b88f
Create Date: 2023-05-14 19:29:31.328513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee7ca416950'
down_revision = '6af7afb1b88f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
