"""New Migration2

Revision ID: d6475546a69e
Revises: 0f8abd56eee8
Create Date: 2023-05-12 08:35:54.344061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6475546a69e'
down_revision = '0f8abd56eee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
