"""New Migration

Revision ID: e61815ea606d
Revises: 626f90c845e1
Create Date: 2023-05-12 08:29:05.943479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61815ea606d'
down_revision = '626f90c845e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QR', sa.Column('LocationID', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'QR', 'Location', ['LocationID'], ['LocationID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'QR', type_='foreignkey')
    op.drop_column('QR', 'LocationID')
    # ### end Alembic commands ###
