"""New Migration

Revision ID: f2e6e7215598
Revises: 6320e35c7e03
Create Date: 2023-05-14 19:38:33.452377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e6e7215598'
down_revision = '6320e35c7e03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
